spring:
  application:
    name: eureka-client
server:
  port: 8081
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 35