server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
  instance:
    prefer-ip-address: true

spring:
  application:
    name: book-service
    cloud:
      config:
        discovery:
          enabled: true
          service-id: config-server
  profiles:
    active: native
  data:
    mongodb:
      database: admin
      username: admin
      password: admin



