spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

    eureka-server-connect-timeout-seconds: 60
    eureka-service-url-poll-interval-seconds: 15
    use-dns-for-fetching-service-urls: false
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    prefer-same-zone-eureka: true
    healthcheck:
      enabled: true
  server:
    expected-client-Renewal-interval-seconds: 20
  instance:
    lease-expiration-duration-in-seconds: 70
