spring:
  application:
    name: config-server
  profiles:
    active: native
server:
  port: 8888
---
spring:
  profiles:
    active: native
  cloud:
    config:
      discovery:
        enabled: true
      server:
        native:
          search-locations: classpath:/ms-config-properties/{application}/{profile}

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

